development:
  adapter: postgresql
  encoding: utf-8
  database: flickrr_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf-8
  database: flickrr_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf-8
  database: flickrr_production
  pool: 5
